# Generated by Django 2.0.6 on 2018-06-29 01:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('busking_django', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Bbs',
            new_name='Event',
        ),
    ]
