# Generated by Django 2.0.6 on 2018-06-29 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('busking_django', '0002_auto_20180629_0116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
