# Generated by Django 2.0.6 on 2018-06-29 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('busking_django', '0003_auto_20180629_0315'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='title',
            new_name='showName',
        ),
        migrations.RemoveField(
            model_name='event',
            name='author',
        ),
        migrations.RemoveField(
            model_name='event',
            name='content',
        ),
        migrations.RemoveField(
            model_name='event',
            name='pw',
        ),
        migrations.AddField(
            model_name='event',
            name='showDescription',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='event',
            name='showGenre',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='event',
            name='showHeart',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='event',
            name='showLocation',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='event',
            name='showTime',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='event',
            name='showTitle',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='event',
            name='userID',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
